# Generated by Django 6.0.4 on 2026-04-16 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dia', 'Dia Inteiro'), ('horario', 'Horário Específico')], default='dia', max_length=10)),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField(blank=True, help_text='Obrigatório para tipo Horário Específico', null=True)),
                ('horario_fim', models.TimeField(blank=True, help_text='Obrigatório para tipo Horário Específico', null=True)),
                ('motivo', models.CharField(blank=True, help_text='Ex: Feriado, Férias, Almoço', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('barbeiro', models.ForeignKey(blank=True, help_text='Deixe vazio para bloquear todos os barbeiros', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_bloqueados', to='core.barbeiro')),
            ],
            options={
                'verbose_name': 'Horário Bloqueado',
                'verbose_name_plural': 'Horários Bloqueados',
                'ordering': ['data', 'horario_inicio'],
            },
        ),
    ]
