# Generated by Django 6.0.4 on 2026-05-12 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_entrada', models.TextField()),
                ('mensagem_saida', models.TextField()),
                ('ip_visitante', models.CharField(blank=True, max_length=50)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversas_website', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversa Website',
                'verbose_name_plural': 'Conversas Website',
                'ordering': ['-criada_em'],
            },
        ),
    ]
