# Generated by Django 6.0.4 on 2026-04-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('pix', 'Pix'), ('credito', 'Crédito'), ('debito', 'Débito'), ('dinheiro', 'Dinheiro')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pago_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='agendamento.agendamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
